nome = str(input('Digite seu nome completo: ')).strip()
string_dividida = nome.split()
print('Muito prazer em te conhecer!')
print('Seu primeiro nome é {}'.format(string_dividida[0]))
print('Seu último nome é {}'.format(string_dividida[len(string_dividida)-1]))
